export type Committee = {
	name: string;
	description: string;
	chairs: string[];
	leads?: string[];
	members: string[];
	image?: string;
};

export const COMMITTEE_DATA: Committee[] = [
	{
		name: "Alumni and Academic Affairs",
		description:
			"Alumni and Academic Affairs builds relationships with UCI faculty, bridges the Student Council with Donald Bren School alumni, and creates opportunities to further students' academic development.",
		chairs: ["Himal Malik"],
		members: [
			"Amir Aunyasopon",
			"Dante Dam",
			"Kaylie Gupta",
			"Marcel Tcheng",
			"Molly Neary",
			"Riya Rallabandi",
			"Sidhant Malik",
			"Steve Yang",
		],
		image: "/committees/aaa.jpg",
	},
	{
		name: "Corporate Outreach",
		description:
			"Corporate Outreach establishes and maintains professional and financial relationships with corporate supporters and alumni. These relationships enable ICS events, informational workshops, and student recruiting.",
		chairs: ["Li Keller"],
		members: [
			"Abinaya Ravi",
			"Anthony Jenanian",
			"Arjun Vivek",
			"Ethan Kosaki",
			"Jasmine Houde",
			"Jason Huang",
			"Qian Ying Wong",
			"Sritha Sthothrabhashyam",
			"Vaishnavi Raghu",
			"Valerie Huynh",
		],
		image: "/committees/corporate.jpg",
	},
	{
		name: "Events",
		description:
			"The Events committee coordinates and hosts a variety of different events designed for the ICS student body. Through our yearly ICS Bonfire, Brain Games, and WebJam competition, Events creates opportunities for ICS students to engage with our community.",
		chairs: ["Audrey Lu", "Matthew Gray"],
		members: [
			"Alan Tran",
			"Alejandro Olivares-Lopez",
			"Anna Lee",
			"Anthony Tam",
			"Arjun Mann",
			"Christopher Young",
			"Dominic Hubschmitt",
			"Emma Narvaez",
			"Evan Garcia",
			"Ira Dharia",
			"Jonathan Chau",
			"Julianna Alderete",
			"Sarah Son",
			"Shayan Halder",
		],
		image: "/committees/events.jpg",
	},
	{
		name: "Graphics",
		description:
			"The Graphics Committee creates graphics for all aspects of ICSSC, from event advertisement graphics to website/project assets, stickers, promotional material, and even merch!",
		chairs: ["Nico Hartman"],
		members: [
			"Anna Li",
			"Audrey Chen",
			"Hailey Chen",
			"Isabella Chang",
			"Jordan Shin",
			"Karena Tran",
			"Katie Li",
			"Mae King",
		],
		image: "/committees/graphics.jpg",
	},
	{
		name: "Projects",
		description:
			"Projects builds real development projects for the UCI community, serving thousands of users. Experience different roles in software development like frontend, backend, and UI/UX. Work in a real development team with version control to prepare you for your career.",
		chairs: ["Andrew Wang", "Kevin Wu"],
		leads: [
			"Alex Espejo",
			"Caden Lee",
			"Ethan Wang",
			"Jacob Moy",
			"Kyle Tran",
			"Lauren Shu",
			"Lex Truong",
			"Sanskar Mishra",
		],
		members: [
			"Aadi Shanker",
			"Abubakr Elmallah",
			"Alex Zhuang",
			"Alexander Liu",
			"Andy Teh",
			"Angela Wang",
			"Anna Chen",
			"Anthony Jenanian",
			"Anushka Dubey",
			"Arshia Aravinthan",
			"Arya Mhaiskar",
			"Arya Palanivel",
			"Atticus Wong",
			"Aurelia Sindhunirmala",
			"Bill Liu",
			"Brendan Lieu",
			"Caleb Wong",
			"Charlie Weinberger",
			"Chris Zecheru",
			"Christopher Sun",
			"Christy Lee",
			"Cindy Liang",
			"Corey Zhong",
			"Dante Dam",
			"Derrick Thrower",
			"Dominic Seung",
			"Ellis Liang",
			"Eren Kim",
			"Eric Tao",
			"Erin Leong",
			"Ethan Chao",
			"Ethan Kosaki",
			"Ethan Tran",
			"Evelyn Garcia",
			"Francis Escares Padua",
			"Grace Yan",
			"Hayden Karp",
			"Isaac Nguyen",
			"Isaac Phoon",
			"Jason Lin",
			"Jason Nguyen",
			"Jay Wu",
			"Jeremiah Soe",
			"Jerry Nguyen",
			"June Kim",
			"Justin Siek",
			"Kailee Kaocharoen",
			"Kelvin Truong",
			"Lindsay Lim",
			"Majd Katabi",
			"Matt Franklin",
			"Nathan Nguyen",
			"Pranav Batra",
			"Priyansh Shah",
			"Rebecca Su",
			"Samika Bhatkar",
			"Valerie Huynh",
			"Varun Pradeep",
			"Vicky Zhang",
			"Victoria Lee",
			"William Yang",
			"Yitong Liu",
			"Zackery He",
		],
		image: "/committees/projects.jpg",
	},
	{
		name: "Public Relations",
		description:
			"The Public Relations committee keeps the ICS community informed on what's going on with ICS Student Council. PR makes sure our social media is up to date with the latest news on events, workshops, and socials.",
		chairs: ["Andrew Kim"],
		members: [
			"Ashot Gasparyan",
			"Bharathi Kaliraj Shanmugapriya",
			"Jacqueline Nguyen",
			"Jasmine Marwaha",
			"Jeremiah Soe",
			"Kayla Zhang",
			"Mico Sy",
			"Mitali Mittal",
			"Neil Godse",
		],
		image: "/committees/pr.jpg",
	},
];
