export type Committee = {
	name: string;
	description: string;
	members: string[];
	image?: string;
};

export const COMMITTEE_DATA: Committee[] = [
	{
		name: "Alumni and Academic Affairs",
		description:
			"Alumni and Academic Affairs builds relationships with UCI faculty, bridges the Student Council with Donald Bren School alumni, and creates opportunities to further students' academic development.",

		members: [
			"Clara Chen",
			"Darren Huynh",
			"Marcel Tcheng",
			"Riya Sri Rallabandi",
			"Ashley Zhou",
			"Roger Chen",
			"Julia Nguyen",
			"Dante Dam",
			"Himal Malik",
		],
		image: "/committees/aaa.jpg",
	},
	{
		name: "Corporate Outreach",
		description:
			"Corporate Outreach establishes and maintains professional and financial relationships with corporate supporters and alumni. These relationships enable ICS events, informational workshops, and student recruiting.",
		members: [
			"Rish Sharma",
			"Aaditya Borse",
			"Luis Lopez",
			"Paris Haraguchi",
			"Kaylee Doliente",
			"Valerie Huynh",
			"Noah Tizon",
			"Jasen Mark",
			"Joshua Ji",
			"Avery Horton",
		],
	},
	{
		name: "Events",
		description:
			"The Events committee coordinates and hosts a variety of different events designed for the ICS student body. Through our yearly ICS Bonfire, Brain Games, and WebJam competition, Events creates opportunities for ICS students to engage with our community.",
		members: [
			"Arnav Nigam",
			"Calvin Nguyen",
			"Jeffrey Meng",
			"Rebecca Ahn",
			"Nicole Nguyen",
			"Rachel Kline",
			"Alan Tran",
			"Audrey Lu",
			"Sarah Son",
			"Shayan Halder",
			"Anna Lee",
			"Anthony Tam",
			"Christopher Young",
			"Arjun Mann",
			"Julianna Alderete",
			"Jonathan Chau",
			"Matthew Gray",
		],
	},
	{
		name: "Graphics",
		description:
			"The Graphics Committee creates graphics for all aspects of ICSSC, from event advertisement graphics to website/project assets, stickers, promotional material, and even merch!",
		members: [
			"Michelle Huang",
			"Alaina Klaes",
			"Karena Tran",
			"Xavier Chung",
			"Mae King",
			"Nico Hartman",
			"Audrey Chen",
		],
	},
	{
		name: "Projects",
		description:
			"Projects builds real development projects for the UCI community, serving thousands of users. Experience different roles in software development like frontend, backend, and UI/UX. Work in a real development team with version control to prepare you for your career.",
		members: [
			"Alex Espejo",
			"Dalton Adcock",
			"Eric Pedley",
			"Grace Yan",
			"Isaac Nguyen",
			"Jay Wu",
			"Minh Nguyen",
			"Vicky Zhang",
			"Kevin Wu",
			"Aadi Shanker",
			"Andrew Wang",
			"Eddy Chen",
			"Eric Tao",
			"Hyunsu Lim",
			"Jordan Yee",
			"Sanskar Mishra",
			"Yasper De Jong",
			"Aaron Wang",
			"Caden Lee",
			"Charlie Weinberger",
			"Ellis Liang",
			"Ethan Kosaki",
			"Ethan Wang",
			"Jacob Sommer",
			"Timofey Obraztsov",
			"Andy Teh",
			"Jose Gonzalez Jr",
			"Majd Katabi",
			"Matt Franklin",
			"Neel Khare",
			"Caroline David",
			"Daniel Ramos",
			"Grace Jong",
			"Joy Li",
			"Kathleen Pham",
			"Lauren Shu",
			"Anagha Rao",
			"Alexander Liu",
			"Charlie Zhao",
			"Hazel Yu",
			"Bryan Silva",
			"Jason Lin",
			"Katy Huang",
			"Lex Truong",
			"Yuan Yoshimi",
			"Anna Chen",
			"Arya Mhaiskar",
			"Justin Siek",
			"Kyle Tran",
			"Sean Fong",
			"Aryan Mittal",
			"Brendan Lieu",
			"Dang Nguyen Nguyen",
			"Elian Hijmans Malessy",
			"Lauren Yraola",
			"Priyansh Shah",
			"Rebecca Su",
			"Steven Zhou",
			"Tenzin Tsundue",
			"Tyler Yu",
		],
	},
	{
		name: "Public Relations",
		description:
			"The Public Relations committee keeps the ICS community informed on what's going on with ICS Student Council. PR makes sure our social media is up to date with the latest news on events, workshops, and socials.",
		members: [
			"Adhiti Chandramohan",
			"Jeremiah Soe",
			"John Daniel Norombaba",
			"Pranavi Gollanapalli",
			"Jasmine Marwaha",
			"Andrew Kim",
			"Mitali Mittal",
		],
	},
];
