export type Committee = {
    name: string;
    description: string;
    chairs: string[];
    members: string[];
    image?: string;
};

export const COMMITTEE_DATA: Committee[] = [
    {
        name: "Alumni and Academic Affairs",
        description:
            "Alumni and Academic Affairs builds relationships with UCI faculty, bridges the Student Council with Donald Bren School alumni, and creates opportunities to further students' academic development.",
        chairs: ["Ashley Zhou"],
        members: [
            "Clara Chen",
            "Dante Dam",
            "Darren Huynh",
            "Himal Malik",
            "Julia Nguyen",
            "Marcel Tcheng",
            "Riya Sri Rallabandi",
            "Roger Chen",
        ],
        image: "/committees/aaa.jpg",
    },
    {
        name: "Corporate Outreach",
        description:
            "Corporate Outreach establishes and maintains professional and financial relationships with corporate supporters and alumni. These relationships enable ICS events, informational workshops, and student recruiting.",
        chairs: ["Rish Sharma"],
        members: [
            "Aaditya Borse",
            "Avery Horton",
            "Jasen Mark",
            "Joshua Ji",
            "Kaylee Doliente",
            "Luis Lopez",
            "Noah Tizon",
            "Paris Haraguchi",
            "Valerie Huynh",
        ],
        image: "/committees/corporate.jpg",
    },
    {
        name: "Events",
        description:
            "The Events committee coordinates and hosts a variety of different events designed for the ICS student body. Through our yearly ICS Bonfire, Brain Games, and WebJam competition, Events creates opportunities for ICS students to engage with our community.",
        chairs: ["Rachel Kline", "Anna Lee"],
        members: [
            "Alan Tran",
            "Anthony Tam",
            "Arjun Mann",
            "Arnav Nigam",
            "Audrey Lu",
            "Calvin Nguyen",
            "Christopher Young",
            "Jeffrey Meng",
            "Jonathan Chau",
            "Julianna Alderete",
            "Matthew Gray",
            "Nicole Nguyen",
            "Rebecca Ahn",
            "Sarah Son",
            "Shayan Halder",
        ],
        image: "/committees/events.jpg",
    },
    {
        name: "Graphics",
        description:
            "The Graphics Committee creates graphics for all aspects of ICSSC, from event advertisement graphics to website/project assets, stickers, promotional material, and even merch!",
        chairs: ["Michelle Huang", "Alaina Klaes"],
        members: [
            "Audrey Chen",
            "Karena Tran",
            "Mae King",
            "Nico Hartman",
            "Xavier Chung",
        ],
        image: "/committees/graphics.jpg",
    },
    {
        name: "Projects",
        description:
            "Projects builds real development projects for the UCI community, serving thousands of users. Experience different roles in software development like frontend, backend, and UI/UX. Work in a real development team with version control to prepare you for your career.",
        chairs: ["Alexander Liu", "Eddy Chen", "Minh Nguyen"],
        members: [
            "Aadi Shanker",
            "Aaron Wang",
            "Alex Espejo",
            "Anagha Rao",
            "Andrew Wang",
            "Andy Teh",
            "Anna Chen",
            "Arya Mhaiskar",
            "Aryan Mittal",
            "Brendan Lieu",
            "Bryan Silva",
            "Caden Lee",
            "Caroline David",
            "Charlie Weinberger",
            "Charlie Zhao",
            "Dalton Adcock",
            "Daniel Ramos",
            "Dang Nguyen Nguyen",
            "Elian Hijmans Malessy",
            "Ellis Liang",
            "Eric Pedley",
            "Eric Tao",
            "Ethan Kosaki",
            "Ethan Wang",
            "Grace Jong",
            "Grace Yan",
            "Hazel Yu",
            "Hyunsu Lim",
            "Isaac Nguyen",
            "Jacob Sommer",
            "Jason Lin",
            "Jay Wu",
            "Jordan Yee",
            "Jose Gonzalez Jr",
            "Joy Li",
            "Justin Siek",
            "Kathleen Pham",
            "Katy Huang",
            "Kevin Wu",
            "Kyle Tran",
            "Lauren Shu",
            "Lauren Yraola",
            "Lex Truong",
            "Majd Katabi",
            "Matt Franklin",
            "Neel Khare",
            "Priyansh Shah",
            "Rebecca Su",
            "Sanskar Mishra",
            "Sean Fong",
            "Steven Zhou",
            "Tenzin Tsundue",
            "Timofey Obraztsov",
            "Tyler Yu",
            "Vicky Zhang",
            "Yasper De Jong",
            "Yuan Yoshimi",
        ],
        image: "/committees/projects.jpg",
    },
    {
        name: "Public Relations",
        description:
            "The Public Relations committee keeps the ICS community informed on what's going on with ICS Student Council. PR makes sure our social media is up to date with the latest news on events, workshops, and socials.",
        chairs: ["Jeremiah Soe"],
        members: [
            "Adhiti Chandramohan",
            "Andrew Kim",
            "Jasmine Marwaha",
            "John Daniel Norombaba",
            "Mitali Mittal",
            "Pranavi Gollanapalli",
        ],
        image: "/committees/pr.jpg",
    },
];
