import type { Metadata } from "next";

import "./globals.css";

import { Inter } from "next/font/google";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header/header";
import { ReactLenisProvider } from "@/lib/lenis";
import { cn } from "@/lib/utils";
import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const font = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    GeistSans.variable,
                    font.variable,
                    `bg-ic-white font-inter antialiased`
                )}
            >
                <ReactLenisProvider>
                    <div className="flex min-h-[100svh] flex-col">
                        <Header />
                        <div className="mb-16">{children}</div>
                        <Footer />
                    </div>
                </ReactLenisProvider>
            </body>
        </html>
    );
}
